name: Update UNECE RSS feed

on:
  schedule:
    - cron: "0 6 * * *"   # Todos los días a las 6:00 UTC
  workflow_dispatch:       # Permite lanzarlo manualmente desde GitHub Actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests feedgen beautifulsoup4 lxml

      - name: Generate feed.xml
        run: python scripts/generate_feed.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add feed.xml
          git commit -m "Auto-update feed.xml"
          git push
