name: Update UNECE RSS feed

on:
  schedule:
    - cron: "0 6 * * *"  # Todos los días a las 06:00 UTC
  workflow_dispatch:

jobs:
  update-feed:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clonar el repo con token para permisos de push
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # 2️⃣ Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 3️⃣ Instalar dependencias
      - name: Install dependencies
        run: pip install requests beautifulsoup4 feedgen lxml

      # 4️⃣ Ejecutar script
      - name: Generate feed.xml
        run: python scripts/generate_feed.py

      # 5️⃣ Commit y push de feed.xml y seen_links.json
      - name: Commit and push feed.xml
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add feed.xml seen_links.json
          git diff-index --quiet HEAD || git commit -m "Auto-update feed.xml"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
