name: Update UNECE RSS feed

# Ejecuta cada día a las 06:00 UTC y permite ejecución manual
on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  update-feed:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 3️⃣ Instalar dependencias
      - name: Install dependencies
        run: pip install requests beautifulsoup4 feedgen lxml

      # 4️⃣ Ejecutar script para generar feed.xml
      - name: Generate feed.xml
        run: python scripts/generate_feed.py

      # 5️⃣ Commit y push del feed actualizado solo si hay cambios
      - name: Commit and push feed.xml
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add feed.xml
          # Solo hace commit si hay cambios
          git diff-index --quiet HEAD || git commit -m "Auto-update feed.xml"
          git push
